//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.AssignedRequests = new HashSet<AssignedRequests>();
        }
    
        public int IdRequests { get; set; }
        public Nullable<int> IdHelpRequest { get; set; }
        public string ContentRequests { get; set; }
        public string StatusRequests { get; set; }
        public Nullable<System.DateTime> DateRequests { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<int> HoursNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedRequests> AssignedRequests { get; set; }
        public virtual HelpRequest HelpRequest { get; set; }
        public virtual Service Service { get; set; }
    }
}
