//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceForVolunteer
    {
        public int IdServiceForVolunteer { get; set; }
        public Nullable<int> IdVolunteer { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<int> VolunteerHours { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
